# Generated by Django 5.2.1 on 2025-05-21 22:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("data", models.DateField()),
                ("local", models.CharField(max_length=255)),
                ("capacidade", models.PositiveIntegerField()),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="eventos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingresso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("secao", models.CharField(max_length=100)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingressos",
                        to="symple.evento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_compra",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras",
                        to="symple.cliente",
                    ),
                ),
                (
                    "ingressos",
                    models.ManyToManyField(
                        related_name="compras", to="symple.ingresso"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("cartao_credito", "Cartão de Crédito"),
                            ("cartao_debito", "Cartão de Débito"),
                            ("pix", "PIX"),
                            ("boleto", "Boleto Bancário"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=50,
                    ),
                ),
                ("data_pagamento", models.DateTimeField(auto_now_add=True)),
                (
                    "compra",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamento",
                        to="symple.compra",
                    ),
                ),
            ],
        ),
    ]
